---
local: &defaults
  services:
    example:
      protocol: http
      host: localhost
      port: 8080
  tshield:
    sessions_url: http://localhost:4567/sessions
  api:
    health_url: http://localhost:8080/actuator/health
